/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-12 07:31:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainSide_002dbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>GOAT.S</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("                \r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("         \r\n");
      out.write("        $(\"#app\").hover(function(){\r\n");
      out.write("          $(\"#appdiv\").css({\"visibility\":\"visible\"});\r\n");
      out.write("        }, function(){\r\n");
      out.write("          $(\"#appdiv\").css({\"visibility\":\"hidden\"});\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\".myLink\").on(\"click\", function() {\r\n");
      out.write("            window.location.href = \"mainpage_draft2.gos\";\r\n");
      out.write("          });\r\n");
      out.write("       \r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	    	url:\"logincheck.gos\",\r\n");
      out.write("	    	async:false,\r\n");
      out.write("	    	success:gename,\r\n");
      out.write("	    });\r\n");
      out.write("	    function gename(d){\r\n");
      out.write("	    	if(d != \"loginx\"){\r\n");
      out.write("	    		$(\"#gename\").text(d);\r\n");
      out.write("	    	}else{\r\n");
      out.write("	    		location.href=\"loginx.gos\"\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("	    }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("      });\r\n");
      out.write("	    function mypage(){\r\n");
      out.write("	    	location.href=\"gtMypage.gos\";\r\n");
      out.write("	    }\r\n");
      out.write("    </script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("     a:visited {\r\n");
      out.write("       text-decoration: none;\r\n");
      out.write("   }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      html, body {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        max-height: 970px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #appdiv {\r\n");
      out.write("        visibility: hidden;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #appdiv > li {\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background-color: #f7f7f7;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      body {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #body {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #body {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .container {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        width: 300px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      h2 {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 10px 10px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #337ab7;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      h5 {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 5px 0;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #555;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      hr {\r\n");
      out.write("        margin: 20px 0;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        border-top: 1px solid #ddd;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      ul {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      li {\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      .li:hover {\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #div1 {\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #lidiv {\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        max-height: 910px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .con {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("        .hover-element {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  a{\r\n");
      out.write("  	text-decoration: none; \r\n");
      out.write("  	color:#424242;\"\r\n");
      out.write("  }\r\n");
      out.write("  a:visited {\r\n");
      out.write("       text-decoration: none;\r\n");
      out.write("   }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body id=\"body\">\r\n");
      out.write("    <div id=\"body\"> \r\n");
      out.write("      <div id=\"div1\">\r\n");
      out.write("        <h2 onclick=\"location.href='mainpage.gos';\">GOAT.S</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"container con\">\r\n");
      out.write("        <hr />\r\n");
      out.write("        <div id=\"lidiv\">\r\n");
      out.write("			<div style=\"text-align:center;\">\r\n");
      out.write("				<a href=\"javascript:mypage()\" id=\"logincheck\"><img src=\"resources/goats_icon/login_page_id.png\" style=\"width:30px; height:30px;\"><span id=\"gename\"></span>님 반갑습니다.</a>\r\n");
      out.write("			</div>\r\n");
      out.write("          <hr>\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"li\" onclick=\"location.href='mainpage.gos';\">Home</li>\r\n");
      out.write("            <li class=\"li\" onclick=\"location.href='#';\">출장/교육</li>\r\n");
      out.write("            <li class=\"li\" onclick=\"location.href='#';\">휴가</li>\r\n");
      out.write("            <li class=\"li\" onclick=\"location.href='#';\">프로젝트</li>\r\n");
      out.write("            <li class=\"li\" onclick=\"location.href='#';\">공지사항</li>\r\n");
      out.write("            <li class=\"li\" id=\"app\" onclick=\"location.href='mainpage_draft.gos';\">전자결재\r\n");
      out.write("              <div id=\"appdiv\">\r\n");
      out.write("                <ul style=\"position:absolute; margin-top:10px; margin-left:100px;\">\r\n");
      out.write("                   <li><a href=\"document.gos\" style=\"text-decoration: none; color:#424242;\">문서함</a></li>\r\n");
      out.write("                <li>결재함</li>\r\n");
      out.write("                <li>진행함</li>\r\n");
      out.write("                <li>참조함</li>\r\n");
      out.write("                <li>기안함</li>\r\n");
      out.write("                <li>반려함</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
