/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-12 05:46:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainpage_005fdocument_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("     \r\n");
      out.write("    function openFixedWindowSize(url, width, height) {\r\n");
      out.write("        var left = Math.ceil(( window.screen.width / 2) - (width/2));\r\n");
      out.write("        var top = Math.ceil(( window.screen.height / 2) - (height/2)); \r\n");
      out.write("        var windowFeatures = 'width=' + width + ',height=' + height + ',left=' + left + ',top=' + top + ',resizable=no';\r\n");
      out.write("        window.open(url, '_blank', windowFeatures);\r\n");
      out.write("      }\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    	\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("   	  html, body {\r\n");
      out.write("		  height: 100%;\r\n");
      out.write("		  margin: 0;\r\n");
      out.write("		  padding: 0;\r\n");
      out.write("		}\r\n");
      out.write("      body {\r\n");
      out.write("		  display: flex;\r\n");
      out.write("		  flex-direction: column;\r\n");
      out.write("		}\r\n");
      out.write("      body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("      .con {\r\n");
      out.write("		  flex: 1;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("      .container2 {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      .container {\r\n");
      out.write("	    display: flex; /* Flexbox를 적용하여 요소들을 가로로 배치합니다 */\r\n");
      out.write("	    flex-direction: row; /* 요소들을 가로 방향으로 배치합니다 */\r\n");
      out.write("	    justify-content: space-between; /* 각 요소를 좌우로 최대한 벌립니다 */\r\n");
      out.write("	    height: 430.43; \r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("      .container > div {\r\n");
      out.write("        max-width: 800px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .container h3 {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .draft_insert {\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .alert table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .alert th,\r\n");
      out.write("      .alert td {\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .alert th {\r\n");
      out.write("        background-color: #f0f0f0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .work {\r\n");
      out.write("        height: 300px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      #maindiv{\r\n");
      out.write("      	width:100%;\r\n");
      out.write("      	height:100%;\r\n");
      out.write("      }\r\n");
      out.write("      table {\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("		  \r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	  td, th {\r\n");
      out.write("		  border-color: #FFF;\r\n");
      out.write("		  background-color: #FFF;\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container2\" style=\"margin: 0; height:100%;\">\r\n");
      out.write("		<div style=\"height:100%; max-height:970px;\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./mainSide-bar.jsp", out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("      	<div style=\"margin: 0; padding: 0; width:100%;\">\r\n");
      out.write("       	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./Top-bar.jsp", out, false);
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			<br>\r\n");
      out.write("			　<img src=\"resources/goats_icon/home.png\" alt=\"home\" width=\"20\" height=\"20\"> Home > <span style=\"color: #337ab7;\"><b>전자결재</b></span>\r\n");
      out.write("		<table style=\"margin:15px;\">\r\n");
      out.write("		  <tr>\r\n");
      out.write("		    <th style=\"height:40px; border-left:2px solid #337ab7; border-top:2px solid #337ab7; text-align:right;\"><span style=\"color: #337ab7; font-size:13px; border-left: #337ab7;\"><b>기안서</b></span></th>\r\n");
      out.write("		    <th style=\"height:40px; border-top:2px solid #337ab7; border-right:2px solid #337ab7; text-align:left;\"><span style=\"color: #337ab7; font-size:13px; border-left: #337ab7;\"><b>양식</b></span></th>\r\n");
      out.write("		  </tr>\r\n");
      out.write("		  <tr>\r\n");
      out.write("		    <td style=\"height:20px; border-left:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td></td>\r\n");
      out.write("		    <td style=\"height:20px; border-top:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-top:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-top:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-top:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-top:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td width=\"600\" style=\"height:20px; border-top:2px solid #337ab7; border-right:2px solid #337ab7;\"></td>\r\n");
      out.write("		  </tr>\r\n");
      out.write("		  <tr>\r\n");
      out.write("		    <td width=\"140\" style=\"border-left:2px solid #337ab7; text-align:center;\"><a href=\"#\" onclick=\"openFixedWindowSize('gtContractInsertForm', 1033, 600)\"><img src=\"resources/goats_icon/Draft.png\" width=\"45\" height=\"45\"></a></td>\r\n");
      out.write("		    <td style=\"text-align:center;\" width=\"140\"><a href=\"#\" onclick=\"openFixedWindowSize('draftInsertForm.gos', 1033, 600)\"><img src=\"resources/goats_icon/Draft.png\" width=\"45\" height=\"45\"></a></td>\r\n");
      out.write("		    <td style=\"text-align:center;\" width=\"140\"><a href=\"#\" onclick=\"openFixedWindowSize('gtBusinessInsertForm.gos', 1033, 600)\"><img src=\"resources/goats_icon/Draft.png\" width=\"45\" height=\"45\"></a></td>\r\n");
      out.write("		    <td style=\"text-align:center;\" width=\"140\"><a href=\"#\" onclick=\"openFixedWindowSize('gtVacationInsertForm.gos', 1033, 600)\"><img src=\"resources/goats_icon/Draft.png\" width=\"45\" height=\"45\"></a></td>\r\n");
      out.write("		    <td style=\"text-align:center;\" width=\"140\"><a href=\"#\" onclick=\"openFixedWindowSize('spendInsertForm.gos', 1033, 600)\"><img src=\"resources/goats_icon/Draft.png\" width=\"45\" height=\"45\"></a></td>\r\n");
      out.write("		    <td style=\"text-align:center;\" width=\"140\"><a href=\"#\" onclick=\"openFixedWindowSize('resignationInsertForm.gos', 1033, 600)\"><img src=\"resources/goats_icon/Draft.png\" width=\"45\" height=\"45\"></a></td>\r\n");
      out.write("		    <td width=\"600\" style=\"height:20px;\"></td>\r\n");
      out.write("		    <td width=\"600\" style=\"height:20px; border-right:2px solid #337ab7;\"></td>\r\n");
      out.write("		  </tr>\r\n");
      out.write("		  <tr>\r\n");
      out.write("		    <td style=\"text-align:center; height:20px; border-left:2px solid #337ab7; font-size:13px\"><b>기안서(계약)</b></td>\r\n");
      out.write("		    <td style=\"text-align:center; font-size:13px\"><b>기안서</b></td>\r\n");
      out.write("		    <td style=\"text-align:center; font-size:13px\"><b>출장계획서</b></td>\r\n");
      out.write("		    <td style=\"text-align:center; font-size:13px\"><b>휴가신청서</b></td>\r\n");
      out.write("		    <td style=\"text-align:center; font-size:13px\"><b>지출결의서</b></td>\r\n");
      out.write("		    <td style=\"text-align:center; font-size:13px\"><b>사직서</b></td>\r\n");
      out.write("		    <td></td>\r\n");
      out.write("		    <td width=\"600\" style=\"height:20px; border-right:2px solid #337ab7;\"></td>\r\n");
      out.write("		  </tr>\r\n");
      out.write("		  \r\n");
      out.write("		  <tr>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7; border-left:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7;\"></td>\r\n");
      out.write("		    <td style=\"height:20px; border-bottom:2px solid #337ab7; border-right:2px solid #337ab7;\"\"></td>\r\n");
      out.write("		  </tr>\r\n");
      out.write("		</table>	 \r\n");
      out.write("		</div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
