/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-12 07:27:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypageinf_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"UTF-8\">\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("		<title>Document</title>\r\n");
      out.write("		\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			$(document).on(\"click\", \"#btn\", function() {\r\n");
      out.write("				$(\"#wrapper2\").css({\r\n");
      out.write("					\"visibility\" : \"hidden\"\r\n");
      out.write("				});\r\n");
      out.write("					\r\n");
      out.write("				alert(\"asdasd\");\r\n");
      out.write("				\r\n");
      out.write("				$(\"#wrapper3\").css({\r\n");
      out.write("					\"visibility\" : \"visible\"\r\n");
      out.write("				});		\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(document).on(\"click\", \"#gbtn\", function() {\r\n");
      out.write("				$(\"#wrapper2\").css({\r\n");
      out.write("					\"visibility\" : \"visible\"\r\n");
      out.write("				});\r\n");
      out.write("					\r\n");
      out.write("				alert(\"asdasd\");\r\n");
      out.write("				\r\n");
      out.write("				$(\"#wrapper3\").css({\r\n");
      out.write("					\"visibility\" : \"hidden\"\r\n");
      out.write("				});		\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("		</script>\r\n");
      out.write("	</head>\r\n");
      out.write("		<style src=\"text/css\">\r\n");
      out.write("		\r\n");
      out.write("		/* 기본 레이아웃 */\r\n");
      out.write("		.wrapper2 {\r\n");
      out.write("			position : absolute ;\r\n");
      out.write("			z-index: 2;\r\n");
      out.write("			background-color: #fff;\r\n");
      out.write("			margin-top: 19px;\r\n");
      out.write("			margin-right: 10px;\r\n");
      out.write("			width: 600px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.section2 {\r\n");
      out.write("	\r\n");
      out.write("			margin: 2px;\r\n");
      out.write("			display: flex;\r\n");
      out.write("			margin-bottom: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		/* 홀수번째 .article 조정 */\r\n");
      out.write("		.article2:nth-of-type(odd) {\r\n");
      out.write("\r\n");
      out.write("			padding-left: 5px;\r\n");
      out.write("			width: 25%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 짝수번째 .article 조정 */\r\n");
      out.write("		.article2:nth-of-type(even) {\r\n");
      out.write("\r\n");
      out.write("			width: 81%;\r\n");
      out.write("			padding-left: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		bi {\r\n");
      out.write("			width: 81%;\r\n");
      out.write("			margin-right: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	/*===============================================================  */	\r\n");
      out.write("		/* 기본 레이아웃 */\r\n");
      out.write("		.wrapper3 {\r\n");
      out.write("			position : absolute ;\r\n");
      out.write("			z-index: 1;\r\n");
      out.write("			background-color: #fff;\r\n");
      out.write("			margin-top: 18px;\r\n");
      out.write("			margin-right: 10px;\r\n");
      out.write("			width: 600px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.section3 {\r\n");
      out.write("	\r\n");
      out.write("			margin: 2px;\r\n");
      out.write("			display: flex;\r\n");
      out.write("			margin-bottom: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* 홀수번째 .article 조정 */\r\n");
      out.write("		.article3:nth-of-type(odd) {\r\n");
      out.write("			padding-left: 5px;\r\n");
      out.write("			width: 25%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 짝수번째 .article 조정 */\r\n");
      out.write("		.article3:nth-of-type(even) {\r\n");
      out.write("			width: 75%;\r\n");
      out.write("			padding-left: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#wrapper3 {\r\n");
      out.write("			visibility: hidden;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.wrap {\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("		</style>\r\n");
      out.write("	\r\n");
      out.write("	<body>\r\n");
      out.write("		<div class=\"wrap\">\r\n");
      out.write("			<div class=\"wrapper2\" id=\"wrapper2\" >\r\n");
      out.write("				<div class=\"content2\">\r\n");
      out.write("					<input type=\"button\" value=\"내정보\"><input type=\"button\" value=\"비밀번호 변경\" id=\"btn\">\r\n");
      out.write("					<hr>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"content2\">\r\n");
      out.write("					<div class=\"section2\">\r\n");
      out.write("						<div class=\"article2\">email</div>	\r\n");
      out.write("                        <input style=\"width: 450px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section2\">\r\n");
      out.write("						<div class=\"article2\">주소</div>\r\n");
      out.write("                        <input style=\"width: 450px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section2\">\r\n");
      out.write("						<div class=\"article2\">전화번호</div>\r\n");
      out.write("                        <input style=\"width: 450px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section2\">\r\n");
      out.write("						<div class=\"article2\">비상연락망1</div>\r\n");
      out.write("						<div class=\"article2\">\r\n");
      out.write("							<select width=\"90%;\">\r\n");
      out.write("                                <option>--선택--</option>\r\n");
      out.write("								<option>1</option>\r\n");
      out.write("								<option>2</option>\r\n");
      out.write("								<option>3</option>\r\n");
      out.write("                                <input name = bi>\r\n");
      out.write("							</select>\r\n");
      out.write("                       \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section2\">\r\n");
      out.write("						<div class=\"article2\">비상연락망2</div>\r\n");
      out.write("						<div class=\"article2\">\r\n");
      out.write("							<select>\r\n");
      out.write("                                <option>--선택--</option>\r\n");
      out.write("								<option>1</option>\r\n");
      out.write("								<option>2</option>\r\n");
      out.write("								<option>3</option>\r\n");
      out.write("                                <input name = bi>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section2\">\r\n");
      out.write("						<div class=\"article2\"></div>\r\n");
      out.write("						<div class=\"article2\">\r\n");
      out.write("							<input type=\"button\" value=\"저장\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		<!-- 		===============================================================   -->\r\n");
      out.write("			<div class=\"wrapper3\" id=\"wrapper3\">\r\n");
      out.write("				<div class=\"content3\">\r\n");
      out.write("					<input type=\"button\" value=\"내정보\" id=\"gbtn\"><input type=\"button\" value=\"비밀번호 변경\" >\r\n");
      out.write("					<hr>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"content3\"></div>\r\n");
      out.write("					<div class=\"section3\">\r\n");
      out.write("						<div class=\"article3\">기존 비밀번호</div>\r\n");
      out.write("	                    <input type=\"text\" style=\"width: 450px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section3\">\r\n");
      out.write("						<div class=\"article3\">새 비밀번호</div>\r\n");
      out.write("	                    <input type=\"text\" style=\"width: 450px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("	              \r\n");
      out.write("					<div class=\"section3\">\r\n");
      out.write("						<div class=\"article3\">새 비밀번호 확인</div>\r\n");
      out.write("	                    <input type=\"text\" style=\"width: 450px;\">\r\n");
      out.write("					</div>\r\n");
      out.write("	                <div  class=\"section3\">\r\n");
      out.write("	                    <div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"article3\">   \r\n");
      out.write("	                        <small class=\"small\">비밀번호 8자리 이상 입력하십쇼 </small> \r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("					<div class=\"section3\">\r\n");
      out.write("						<div class=\"article3\"></div>\r\n");
      out.write("						<div class=\"article3\">\r\n");
      out.write("							<input type=\"button\" value=\"저장\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
