/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-12 07:27:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.vacation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gt.s.kos.business.vo.GtBusinessVO;
import com.gt.s.common.CodeUtil;

public final class vacationInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gt.s.kos.business.vo.GtBusinessVO");
    _jspx_imports_classes.add("com.gt.s.common.CodeUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String gename = (String) request.getAttribute("ge_name"); 
      out.write('\r');
      out.write('\n');
 String dept = (String) request.getAttribute("dept"); 
      out.write('\r');
      out.write('\n');
 String title = (String) request.getAttribute("title"); 
      out.write('\r');
      out.write('\n');
 String gehp = (String) request.getAttribute("gehp"); 
      out.write('\r');
      out.write('\n');
 String titleNum = CodeUtil.title_gubun(title); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	\r\n");
      out.write("	<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.quilljs.com/1.3.6/quill.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("			\r\n");
      out.write("			$(document).ready(function() {\r\n");
      out.write("				\r\n");
      out.write("				// 작성자\r\n");
      out.write("				var gename = \"");
      out.print(gename);
      out.write("\";\r\n");
      out.write("				var dept = \"");
      out.print(dept);
      out.write("\";\r\n");
      out.write("				var title = \"");
      out.print(title);
      out.write("\";\r\n");
      out.write("				var titlenum = \"");
      out.print(titleNum);
      out.write("\";\r\n");
      out.write("				titlenum = \"3\";\r\n");
      out.write("				var writer = dept + \" \" + gename + \" \" + title;\r\n");
      out.write("				\r\n");
      out.write("				// 연락처\r\n");
      out.write("				var hp = \"");
      out.print(gehp);
      out.write("\";\r\n");
      out.write("				\r\n");
      out.write("				hp = \"010-9891-0000\";\r\n");
      out.write("					\r\n");
      out.write("				$(\"#gehp1\").text(hp);\r\n");
      out.write("	\r\n");
      out.write("				alert(gename);\r\n");
      out.write("				$(\"#writer1\").text(writer);\r\n");
      out.write("				$(\"#writer\").val(writer);\r\n");
      out.write("				\r\n");
      out.write("				document.getElementById(\"date\").innerText = new Date().toISOString().slice(0, 10);\r\n");
      out.write("				\r\n");
      out.write("				// 상신\r\n");
      out.write("				$(document).on(\"click\", \"#sbtn\", function() {\r\n");
      out.write("					\r\n");
      out.write("					// 연락처\r\n");
      out.write("					$(\"#gehp\").val(hp);\r\n");
      out.write("					\r\n");
      out.write("					// 결재선\r\n");
      out.write("					var hu1 = $(\"#hu1\").text()\r\n");
      out.write("					var hu2 = $(\"#hu2\").text()\r\n");
      out.write("					var hu3 = $(\"#hu3\").text()\r\n");
      out.write("					var hu4 = $(\"#hu4\").text()\r\n");
      out.write("					var hu5 = $(\"#hu5\").text()\r\n");
      out.write("					\r\n");
      out.write("					$(\"#hu1_1\").val(hu1);\r\n");
      out.write("					$(\"#hu2_1\").val(hu2);\r\n");
      out.write("					$(\"#hu3_1\").val(hu3);\r\n");
      out.write("					$(\"#hu4_1\").val(hu4);\r\n");
      out.write("					$(\"#hu5_1\").val(hu5);\r\n");
      out.write("					\r\n");
      out.write("					alert(hu1);\r\n");
      out.write("					alert($(\"#hu1_1\").val());\r\n");
      out.write("					\r\n");
      out.write("					var dep1 = $(\"#dep1\").text()\r\n");
      out.write("					var dep2 = $(\"#dep2\").text()\r\n");
      out.write("					var dep3 = $(\"#dep3\").text()\r\n");
      out.write("					var dep4 = $(\"#dep4\").text()\r\n");
      out.write("					var dep5 = $(\"#dep5\").text()\r\n");
      out.write("					\r\n");
      out.write("					$(\"#dept1_1\").val(dep1);\r\n");
      out.write("					$(\"#dept2_1\").val(dep2);\r\n");
      out.write("					$(\"#dept3_1\").val(dep3);\r\n");
      out.write("					$(\"#dept4_1\").val(dep4);\r\n");
      out.write("					$(\"#dept5_1\").val(dep5);\r\n");
      out.write("\r\n");
      out.write("					alert(dep1);\r\n");
      out.write("					alert($(\"#dept1_1\").val());\r\n");
      out.write("					\r\n");
      out.write("					var cc = $(\"#reference\").text();\r\n");
      out.write("					\r\n");
      out.write("					var aa = cc.replaceAll(\", \", \"/\");\r\n");
      out.write("					\r\n");
      out.write("					console.log(\">>> \" +  aa);\r\n");
      out.write("					\r\n");
      out.write("					// input 히든에 벨류 값 보냄\r\n");
      out.write("					$(\"#reference\").val(aa);\r\n");
      out.write("	\r\n");
      out.write("					let gvnum = document.getElementById(\"gvnum\").value;\r\n");
      out.write("					alert(gvnum);\r\n");
      out.write("					\r\n");
      out.write("					// 메모 보내기\r\n");
      out.write("					var ql = $('.ql-editor').html();   \r\n");
      out.write("					var qui = $(\"#quill_html\").val(ql);\r\n");
      out.write("		               \r\n");
      out.write("					alert(\"memo : > \" + qui.val());\r\n");
      out.write("					\r\n");
      out.write("					$(\"#quill_html\").val(qui.val());\r\n");
      out.write("					let dataParam = $(\"#form01\").serialize(); // text들이 정상적으로 DB에 전송 될 시\r\n");
      out.write("	\r\n");
      out.write("					// 파일 업로드\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"gtVacationInsert.gos\",\r\n");
      out.write("						data : dataParam,\r\n");
      out.write("						success : function(res) {\r\n");
      out.write("							alert(res);\r\n");
      out.write("							if (res == \"OK\") {\r\n");
      out.write("	\r\n");
      out.write("								$(\"#gvfile_form\").attr({\r\n");
      out.write("									// file만 단독으로 업로드 시킨다.\r\n");
      out.write("									\"action\" : \"gtVacationInsertFile.gos\",\r\n");
      out.write("									\"method\" : \"POST\",\r\n");
      out.write("									\"enctype\" : \"multipart/form-data\" // 파일 업로드 시에는 enctype이 꼭 있어야함\r\n");
      out.write("								}).submit();\r\n");
      out.write("							} else {\r\n");
      out.write("								alert(\"입력 실패\");\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("						error : function(e) {\r\n");
      out.write("							console.log(e.responseText)\r\n");
      out.write("						}\r\n");
      out.write("					});				\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				// 채번\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"gtVacationChanbun.gos\",\r\n");
      out.write("					type : \"GET\",\r\n");
      out.write("					success : function(res) {\r\n");
      out.write("	\r\n");
      out.write("					var gvnum = res;\r\n");
      out.write("	\r\n");
      out.write("						alert(typeof (gvnum));\r\n");
      out.write("						$(\"#gvnum1\").text(gvnum);\r\n");
      out.write("						\r\n");
      out.write("						$(\"#gvnum\").val(gvnum);\r\n");
      out.write("					},\r\n");
      out.write("					error : function(e) {\r\n");
      out.write("						alert(\"gtVacationChanbun\");\r\n");
      out.write("						console.log(e.responseText)\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("	\r\n");
      out.write("				//대결자\r\n");
      out.write("				var titlenum = \"4\";\r\n");
      out.write("	\r\n");
      out.write("				if (parseInt(titlenum) >= 4) {\r\n");
      out.write("					$.ajax({\r\n");
      out.write("	\r\n");
      out.write("						url : \"goatsEmployeeSelect.gos\",\r\n");
      out.write("						data : {\r\n");
      out.write("							dept : \"개발2팀\"\r\n");
      out.write("							\r\n");
      out.write("						},\r\n");
      out.write("						success : function(res) {\r\n");
      out.write("							console.log(res);\r\n");
      out.write("							selectDept(res);\r\n");
      out.write("						},\r\n");
      out.write("						error : function(e) {\r\n");
      out.write("							console.log(e.responseText);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				function selectDept(dept) {\r\n");
      out.write("	\r\n");
      out.write("					var a = dept.split('/');\r\n");
      out.write("					console.log(a);\r\n");
      out.write("					var select = \"\";\r\n");
      out.write("					for (var i = 0; i < a.length - 1; i++) {\r\n");
      out.write("	\r\n");
      out.write("						var b = a[i].replaceAll(\",\", \"/\")\r\n");
      out.write("						var selectOption = \"<option value=\" + b + \">\" + b + \"</option>\";\r\n");
      out.write("						select += selectOption;\r\n");
      out.write("					}\r\n");
      out.write("						console.log(select);\r\n");
      out.write("	\r\n");
      out.write("					$(\"#decianother\").append(select);\r\n");
      out.write("	\r\n");
      out.write("				};\r\n");
      out.write("	\r\n");
      out.write("				// 기간 계산 \r\n");
      out.write("				$(\"#gvenddate\").change(function() {\r\n");
      out.write("					\r\n");
      out.write("					let sd = document.querySelector(\"#gvstartdate\").value;\r\n");
      out.write("					let ed = document.querySelector(\"#gvenddate\").value;\r\n");
      out.write("					\r\n");
      out.write("					sd = new Date(sd);\r\n");
      out.write("					ed = new Date(ed);\r\n");
      out.write("	\r\n");
      out.write("					if (ed <= sd) {\r\n");
      out.write("						alert(\"날짜를 확인해주십쇼\");\r\n");
      out.write("						$(\"#gvenddate\").val(\"\");\r\n");
      out.write("						\r\n");
      out.write("						return false;\r\n");
      out.write("					}\r\n");
      out.write("	\r\n");
      out.write("					alert(sd);\r\n");
      out.write("					alert(ed);\r\n");
      out.write("	\r\n");
      out.write("					dd = ed - sd;\r\n");
      out.write("					\r\n");
      out.write("					let datem = 24 * 60 * 60 * 1000;\r\n");
      out.write("	\r\n");
      out.write("					let date = dd / datem + \"일\";\r\n");
      out.write("					\r\n");
      out.write("					// document.getElementById(\"time\").innerText =  date;\r\n");
      out.write("					$(\"#gvdays1\").text(date);\r\n");
      out.write("					$(\"#gvdays\").val(date);\r\n");
      out.write("\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("				$(document).on(\"click\", \"#gbtn\", function() {\r\n");
      out.write("					$(\"#approvalline\").css({\r\n");
      out.write("						\"visibility\" : \"visible\"\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("			});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("	.button-container {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.initial-size {\r\n");
      out.write("		min-height: 200px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 		th {\r\n");
      out.write("				background-color: #f2f2f2;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			table {\r\n");
      out.write("				border-collapse: collapse;\r\n");
      out.write("				width: 1033px;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			th {\r\n");
      out.write("				border: 1px solid black;\r\n");
      out.write("				padding: 8px;\r\n");
      out.write("				text-align: center;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			td {\r\n");
      out.write("				border: 1px solid black;\r\n");
      out.write("				padding: 8px;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			div {\r\n");
      out.write("				width: 1033px;\r\n");
      out.write("			} */\r\n");
      out.write("	#approvalline {\r\n");
      out.write("		visibility: hidden;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		background-color: #fff;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<div id=\"approvalline\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../approvalline/select.jsp", out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<form name=\"form01\" id=\"form01\">\r\n");
      out.write("			<div class=\"button-container\">\r\n");
      out.write("				<button type=\"button\" id=\"gbtn\">결재선지정</button>\r\n");
      out.write("				<button type=\"button\" id=\"sbtn\">상신</button>\r\n");
      out.write("				<button type=\"button\" id=\"cbtn\">취소</button>\r\n");
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h2 align=\"center\">휴가 신청서</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<table id=\"gv_form\">\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<th width=\"120px\">문서번호</th>\r\n");
      out.write("					<td width=\"230px\" id=\"gvnum1\"></td>\r\n");
      out.write("					<th width=\"120px\">보안구분</th>\r\n");
      out.write("					<td width=\"230px\">비공개</td>\r\n");
      out.write("					<th width=\"120px\">보존연한</th>\r\n");
      out.write("					<td width=\"230px\">5년</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<th width=\"100px\">작성자</th>\r\n");
      out.write("					<td width=\"230px%\" id=\"writer1\">\r\n");
      out.write("					<th width=\"100px\">작성일자</th>\r\n");
      out.write("					<td width=\"230px\" id=\"date\"></td>\r\n");
      out.write("					<th width=\"120px\">대결자</th>\r\n");
      out.write("					<td width=\"230px\"><select name=\"decianother\" id=\"decianother\">\r\n");
      out.write("					<option value=\"-\"> - </option></select></td>\r\n");
      out.write("					<!-- 작성일자 -->\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("			<table id=\"table1\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"19px\">순서</th>\r\n");
      out.write("					<th width=\"83px\">구분</th>\r\n");
      out.write("					<th width=\"14px\">결재자</th>\r\n");
      out.write("					<th width=\"14px\">부서</th>\r\n");
      out.write("					<th width=\"14px\">상태</th>\r\n");
      out.write("					<th width=\"14px\">결재일</th>\r\n");
      out.write("					<th width=\"14px\">결재의견</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td>1</td>\r\n");
      out.write("					<td id=\"snag1\"></td>\r\n");
      out.write("					<td id=\"hu1\"></td>\r\n");
      out.write("					<td id=\"dep1\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td>2</td>\r\n");
      out.write("					<td id=\"snag2\"></td>\r\n");
      out.write("					<td id=\"hu2\"></td>\r\n");
      out.write("					<td id=\"dep2\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td>3</td>\r\n");
      out.write("					<td id=\"snag3\"></td>\r\n");
      out.write("					<td id=\"hu3\"></td>\r\n");
      out.write("					<td id=\"dep3\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td>4</td>\r\n");
      out.write("					<td id=\"snag4\"></td>\r\n");
      out.write("					<td id=\"hu4\"></td>\r\n");
      out.write("					<td id=\"dep4\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td>5</td>\r\n");
      out.write("					<td id=\"snag5\"></td>\r\n");
      out.write("					<td id=\"hu5\"></td>\r\n");
      out.write("					<td id=\"dep5\"></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("			<table id=\"cham1\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"120px\">참 조</th>\r\n");
      out.write("					<td id=\"reference\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr align=\"left\">\r\n");
      out.write("					<th width=\"120px\">제 목</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"gvsubject\" size=\"100px\"\r\n");
      out.write("						style=\"width: 820px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr align=\"left\">\r\n");
      out.write("					<th width=\"120px\">일 시</th>\r\n");
      out.write("					<td width=\"346px\" colspan=\"3\"><input type=\"date\"\r\n");
      out.write("						name=\"gvstartdate\" id=\"gvstartdate\" max=\"2060-12-31\"\r\n");
      out.write("						min=\"1950-01-01\"> ~ <input type=\"date\" name=\"gvenddate\"\r\n");
      out.write("						id=\"gvenddate\" max=\"2060-12-31\" min=\"1950-01-01\"></td>\r\n");
      out.write("	\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"120px\">기 간</th>\r\n");
      out.write("					<td width=\"700px\" id=\"gvdays1\"></td>\r\n");
      out.write("					<th width=\"100px\">구 분</th>\r\n");
      out.write("					<td align=\"center\"><select name=\"gvtype\">\r\n");
      out.write("							<option value=\"-\"> - </option>\r\n");
      out.write("							<option value=\"연차\">연차</option>\r\n");
      out.write("							<option value=\"반차\">반차</option>\r\n");
      out.write("							<option value=\"월차\">월차</option>\r\n");
      out.write("					</select></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<table>\r\n");
      out.write("				<br>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"120px\">사 유</th>\r\n");
      out.write("					<td colspan=\"3\"><input type=\"text\" name=\"gvreasons\" size=\"100%\"\r\n");
      out.write("						style=\"width: 820px\"></td>\r\n");
      out.write("	\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"120px\">연 락 처</th>\r\n");
      out.write("					<td id=\"gehp1\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<br>\r\n");
      out.write("			</table>\r\n");
      out.write("			<table>\r\n");
      out.write("				<th width=\"120px\">비고</th>\r\n");
      out.write("				<br>\r\n");
      out.write("			</table>\r\n");
      out.write("			<div id=\"editor\" class=\"initial-size\"></div>\r\n");
      out.write("			<script>\r\n");
      out.write("				var quill = new Quill('#editor', {\r\n");
      out.write("				// Quill 설정 옵션\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("				// 작성 영역 클릭 시 이벤트 처리\r\n");
      out.write("				var editorContainer = document.querySelector('#editor');\r\n");
      out.write("				editorContainer.addEventListener('click', function() {\r\n");
      out.write("					quill.focus(); // 작성 영역으로 포커스 이동\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("				var toolbarOptions = [ [ 'bold', 'italic', 'underline', 'strike' ],\r\n");
      out.write("						[ 'link', 'image' ], [ {\r\n");
      out.write("							'list' : 'ordered'\r\n");
      out.write("						}, {\r\n");
      out.write("							'list' : 'bullet'\r\n");
      out.write("						} ], [ {\r\n");
      out.write("							'header' : [ 1, 2 ]\r\n");
      out.write("						} ] ];\r\n");
      out.write("	\r\n");
      out.write("				var quill = new Quill('#editor', {\r\n");
      out.write("					modules : {\r\n");
      out.write("						toolbar : toolbarOptions\r\n");
      out.write("					},\r\n");
      out.write("					theme : 'snow'\r\n");
      out.write("				});\r\n");
      out.write("	\r\n");
      out.write("				function myFunction() {\r\n");
      out.write("					alert(\"gd\");\r\n");
      out.write("				}\r\n");
      out.write("			</script>\r\n");
      out.write("	\r\n");
      out.write("			<div>\r\n");
      out.write("				<!-- 다른 곳에 있는 데이터를 담는 통을 해준다.-->\r\n");
      out.write("			 	<input type=\"hidden\" id=\"quill_html\" name=\"gvmemo\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"reference\" name=\"reference\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"hu1_1\" name=\"approver1\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"hu2_1\" name=\"approver2\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"hu3_1\" name=\"approver3\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"hu4_1\" name=\"approver4\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"hu5_1\" name=\"approver5\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"dept1_1\" name=\"dep1\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"dept2_1\" name=\"dep2\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"dept3_1\" name=\"dep3\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"dept4_1\" name=\"dep4\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" id=\"dept5_1\" name=\"dep5\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" name=\"writer\" id=\"writer\" value=\"\"> \r\n");
      out.write("				<input type=\"hidden\" id=\"dept\" name=\"dept\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" name=\"gvnum\" id=\"gvnum\" value=\"\"> \r\n");
      out.write("				<input type=\"hidden\" name=\"gehp\" id=\"gehp\" value=\"\">\r\n");
      out.write("				<input type=\"hidden\" name=\"gvdays\" id=\"gvdays\" value=\"\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<br>\r\n");
      out.write("		<form id=\"gvfile_form\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"120px\">첨부파일</th>\r\n");
      out.write("					<td><input type=\"file\" name=\"gvfile\" id=\"gvfile\" size=\"100%\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("		<br>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
